export const CONFIG = {
  SUPABASE_URL: '%SUPABASE_URL%',
  SUPABASE_KEY: '%SUPABASE_KEY%',
  ADMIN_EMAIL: '%ADMIN_EMAIL%',
  DEFAULT_PASS: '%DEFAULT_PASS%'
};

const supabase = createClient(CONFIG.SUPABASE_URL, CONFIG.SUPABASE_KEY);
